In [177]:
import numpy as np
import matplotlib.pyplot as plt
import random
import csv

# Hostels

The file lights-count-hostel.csv has a count of lights only for Hostel 5 and 7. Simply multiplying this count by 2 will give us an order of magnitude count of the total lights in all hostels.

In [178]:
file_1 = open('lights-count-hostel.csv')
csvreader = csv.reader(file_1)
rows = []
for row in csvreader:
        rows.append(row)
lights_count_hostel = np.array(rows).astype('float64')*2

In [179]:
file_2 = open('lights-time-hostel.csv')
csvreader = csv.reader(file_2)
rows = []
for row in csvreader:
        rows.append(row)
lights_time_hostel = np.array(rows).astype('float64')

In [180]:
file_3 = open('lights-power-rating-hostel.csv')
csvreader = csv.reader(file_3)
rows = []
for row in csvreader:
        rows.append(row)
lights_power_rating_hostel = np.array(rows).astype('float64')

In [181]:
energy_consumption_hostel_array = np.multiply(np.multiply(lights_count_hostel, lights_time_hostel), lights_power_rating_hostel)

In [182]:
total_for_each_light_type_hostel = np.sum(energy_consumption_hostel_array, axis =0)
total_for_each_light_type_hostel

array([120384. ,      0. , 127344. ,  63360. ,  98514. ,  38880. ,
            0. , 138240. , 290304. ,  21798.4])

In [183]:
total_hostel = np.sum(energy_consumption_hostel_array)
total_hostel/1000

898.8244

What if we switch to LED alternatives? 

We keep the lights_count and the lights_time matrices as the same. We simply modify the lights_power_rating matrix with the power ratings of LED alternatives.

1. Replace 4 x $T$ with 2 x $L$.
2. Replace 2 x $H$ with 2 x $L$.
3. Replace $T$ with $L$.
4. Replace $C_9$ and $\alpha^2$ with 5 W mini LED tubes.
5. Replace $D$, $U$ and $C_{13}$ with 9 W small LED.

In [193]:
lights_power_rating_hostel_improved = lights_power_rating_hostel
lights_power_rating_hostel_improved[:, 0] = np.full(len(lights_power_rating_hostel[:, 0]), 36)
lights_power_rating_hostel_improved[:, 1] = np.full(len(lights_power_rating_hostel[:, 0]), 36)
lights_power_rating_hostel_improved[:, 2] = np.full(len(lights_power_rating_hostel[:, 0]), 18)
lights_power_rating_hostel_improved[:, 6] = np.full(len(lights_power_rating_hostel[:, 0]), 5)
lights_power_rating_hostel_improved[:, 8] = np.full(len(lights_power_rating_hostel[:, 0]), 5)
lights_power_rating_hostel_improved[:, 3] = np.full(len(lights_power_rating_hostel[:, 0]), 9)
lights_power_rating_hostel_improved[:, 7] = np.full(len(lights_power_rating_hostel[:, 0]), 9)
lights_power_rating_hostel_improved[:, 9] = np.full(len(lights_power_rating_hostel[:, 0]), 9)

In [194]:
energy_consumption_hostel_improved_array = np.multiply(np.multiply(lights_count_hostel, lights_time_hostel), lights_power_rating_hostel_improved)
np.sum(energy_consumption_hostel_improved_array, axis =0)

array([ 60192. ,      0. ,  81864. ,  51840. ,  98514. ,  38880. ,
            0. ,  62208. , 161280. ,  15091.2])

In [203]:
total_hostel_improved = np.sum(energy_consumption_hostel_improved_array)
total_hostel_improved/1000

569.8692

In [204]:
savings_hostel = total_hostel - total_hostel_improved
print("Savings = ", round(savings_hostel/1000, 3), "kWh per day")

Savings =  328.955 kWh per day


# Academic Block

In [188]:
file_4 = open('lights-count-ab.csv')
csvreader = csv.reader(file_4)
rows = []
for row in csvreader:
        rows.append(row)
lights_count_ab = np.array(rows).astype('float64')

In [189]:
file_5 = open('lights-time-ab.csv')
csvreader = csv.reader(file_5)
rows = []
for row in csvreader:
        rows.append(row)
lights_time_ab = np.array(rows).astype('float64')

In [176]:
file_6 = open('lights-power-rating-ab.csv')
csvreader = csv.reader(file_6)
rows = []
for row in csvreader:
        rows.append(row)
lights_power_rating_ab = np.array(rows).astype('float64')

In [190]:
energy_consumption_ab_array = np.multiply(np.multiply(lights_count_ab, lights_time_ab), lights_power_rating_ab)

In [191]:
total_for_each_light_type_ab = np.sum(energy_consumption_ab_array, axis =0)
total_for_each_light_type_ab

array([1568332.8,   59673.6,  135475.2,  158400. ,   19200. ])

In [192]:
total_ab = np.sum(energy_consumption_ab_array)
total_ab/1000

1941.0816

What if we switch to LED alternatives? 

We keep the lights_count and the lights_time matrices as the same. We simply modify the lights_power_rating matrix with the power ratings of LED alternatives.

1. Replace 2 x $H$ with 2 x $L$.
3. Replace $T$ with $L$.
4. Replace $\alpha^2$ with 5 W mini LED tubes.
5. Replace $U$ with 9 W small LED.

In [197]:
lights_power_rating_ab_improved = lights_power_rating_ab
lights_power_rating_ab_improved[:, 0] = np.full(len(lights_power_rating_ab[:, 0]), 36)
lights_power_rating_ab_improved[:, 1] = np.full(len(lights_power_rating_ab[:, 0]), 18)
lights_power_rating_ab_improved[:, 3] = np.full(len(lights_power_rating_ab[:, 0]), 5)
lights_power_rating_ab_improved[:, 4] = np.full(len(lights_power_rating_ab[:, 0]), 9)

In [198]:
energy_consumption_ab_improved_array = np.multiply(np.multiply(lights_count_ab, lights_time_ab), lights_power_rating_ab_improved)
np.sum(energy_consumption_ab_improved_array, axis =0)

array([784166.4,  38361.6, 135475.2,  36000. ,   8640. ])

In [200]:
total_ab_improved = np.sum(energy_consumption_ab_improved_array)
total_ab_improved/1000

1002.6432

In [202]:
savings_ab = total_ab - total_ab_improved
print("Savings (AB) = ", round(savings_ab/1000, 3), "kWh per day")

Savings (AB) =  938.438 kWh per day


In [19]:
total_energy_consumption_due_to_lights = 0.0946*(480+160+166) + 0.1989*(998+1688+2400) + 898 + 1941
total_energy_consumption_due_to_lights

3926.853

In [21]:
print("percentage of energy consumption due to lights", round(total_energy_consumption_due_to_lights/25139 *100,2), "%")

percentage of energy consumption due to lights 15.62 %


In [22]:
savings_calculation = 0.0347*(480+160+166) + 0.096*(998+1688+2400) + 329 + 938
savings_calculation

1783.2242

For $L$, $\ell$ and $m$

In [23]:
N_of_L = 0.041*(480+160+166) + 0.298*(998+1688+2400) + 390 + 2912
N_of_L

4850.674

In [24]:
N_of_ell = 0.103*(480+160+166) + 0.004*(998+1688+2400) + 980 + 40
N_of_ell

1123.362

In [25]:
N_of_m = 0.071*(480+160+166) + 0.046*(998+1688+2400) + 450 + 672
N_of_m 

1413.182

In [26]:
total_cost_replac_drive = 230*4850 + 170*1123 + 150*1413
total_cost_replac_drive

1518360

In [27]:
payback_period = total_cost_replac_drive/14500  #14500 is the savings cost/day.
payback_period

104.71448275862069